alias g='git'
alias ga='git add'
alias gs='git status'
alias gst='gs'  # unlearn using `gst`
alias gb='git branch'
alias gc='git commit'
alias gco='git checkout'
alias gcl='git clone'
alias gpl='git pull'
alias gph='git push'
alias gundo='git reset --soft HEAD^'
alias gwtf='git-wtf' # relies on `bin/git-wtf`, 'git config --global color.ui auto' for color