---
kind: SwitchConfig
version: v1alpha1
refreshIndexAfter: 1h
kubeconfigStores:
  - kind: rancher
    config:
      rancherAPIAddress: https://rancher.asml.com/v3
      rancherToken: TOKEN_HERE # todo: fill via secret manager
    cache:
      kind: filesystem
      config:
        path: ~/.kube/cache
  - kind: gke
    config:
      # optionally set the account. Otherwise, the currently active gcloud account will be used.
      # gcpAccount: my-gcp-account
      authentication:
        authenticationType: gcloud
      # optionally prefer a specific type of endpoint: dns, private, public
      preferredEndpoint: private
      # # optionally limit to certain projects in account
      # projectIDs:
      #   - project-1
      #   - project-2
